import type { Metadata } from 'next'
import { Inter, Roboto} from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  style: ['normal', 'italic'], 
  weight: ['300', '400', '500','700'],
  subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Twitter Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
